# Generated by Django 4.2.7 on 2025-07-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CHOPHOUSE', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline for the business', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Business phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Business email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Business address')),
                ('hours', models.TextField(blank=True, help_text='Business hours (e.g., Mon-Fri: 9AM-6PM)')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL')),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('about_text', models.TextField(blank=True, help_text='About us text for the website')),
                ('delivery_info', models.TextField(blank=True, help_text='Delivery information and policies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
