# Generated by Django 4.2.7 on 2025-07-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Brief description shown in the services grid')),
                ('detailed_description', models.TextField(help_text="Detailed description shown when 'Learn More' is clicked")),
                ('icon', models.CharField(default='fas fa-utensils', help_text='FontAwesome icon class', max_length=50)),
                ('features', models.JSONField(default=list, help_text='List of features/benefits for this service')),
                ('pricing_info', models.TextField(blank=True, help_text='Pricing information or starting prices')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which services appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catering Service',
                'verbose_name_plural': 'Catering Services',
                'ordering': ['order', 'name'],
            },
        ),
    ]
