# Generated by Django 4.2.7 on 2025-07-29 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_campaignrecipient_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productcomment',
            unique_together={('product', 'user_email')},
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user_email')},
        ),
    ]
